[project]
name = "ha-mc-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
    "mcrcon>=0.7.0",
    "requests>=2.32.3",
    "uvicorn[standard]>=0.34.2",
]
