apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-server
  template:
    metadata:
      labels:
        app: mc-server
    spec:
      initContainers:
        - name: migrater
          image: ccr.ccs.tencentyun.com/ha-mc-server/migrater:latest
          restartPolicy: Always
          env:
            - name: MIGRATER_LOCAL_PATH
              value: /mc-save
            - name: MIGRATER_REMOTE_PATH
              value: /mc-save
            - name: SEAWEEDFS_FILER_URL
              value: "http://seaweedfs-filer:8888"
          volumeMounts:
            - name: mc-save
              mountPath: /mc-save
          args:
            - server
            - --port=9000
            - --pull-first
      containers:
        - name: mc-server
          image: ccr.ccs.tencentyun.com/ha-mc-server/mc-server:latest
          ports:
            - containerPort: 25565
            - containerPort: 25575
          volumeMounts:
            - name: mc-save
              mountPath: /mc/save
          command:
            - java
            - -Xms256M
            - -Xmx2G
            - -XX:+UseG1GC
            - -Dfile.encoding=UTF-8
            - -jar
            - spigot-1.21.4.jar
            - --nogui
            - --noconsole
            - -W
            - ./save
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: mc-save
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mc-server
spec:
  selector:
    app: mc-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      name: game
    - protocol: TCP
      port: 25575
      targetPort: 25575
      name: rcon
---
apiVersion: v1
kind: Service
metadata:
  name: migrater
spec:
  selector:
    app: mc-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: saving
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: ccr.ccs.tencentyun.com/ha-mc-server/curl:latest
              imagePullPolicy: IfNotPresent
              args:
                - -X
                - POST
                - http://migrater:9000/push
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
