apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      initContainers:
        - name: migrater
          image: ccr.ccs.tencentyun.com/ha-mc-server/migrater:latest
          restartPolicy: Always
          env:
            - name: MIGRATER_LOCAL_PATH
              value: /mc-save
            - name: MIGRATER_REMOTE_PATH
              value: /mc-save
            - name: SEAWEEDFS_FILER_URL
              value: "http://seaweedfs-filer:8888"
          volumeMounts:
            - name: mc-save
              mountPath: /mc-save
          args:
            - server
            - --port=9000
            - --pull-first
      containers:
        # - name: migrater
        #   image: ccr.ccs.tencentyun.com/qcloud/ubuntu:latest
        #   command:
        #     - sleep
        #     - inf
        #   volumeMounts:
        #     - name: mc-save
        #       mountPath: /mc-save
        - name: web-app
          image: ccr.ccs.tencentyun.com/ha-mc-server/httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mc-save
              mountPath: /usr/local/apache2/htdocs
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: mc-save
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: migrater
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: saving
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: let-migrater-push
              image: ccr.ccs.tencentyun.com/ha-mc-server/curl:latest
              imagePullPolicy: IfNotPresent
              args:
                - -X
                - POST
                - http://migrater:9000/push
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
