apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-volume
spec:
  serviceName: seaweedfs-volume
  replicas: 3
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
        - name: seaweedfs-volume
          image: ccr.ccs.tencentyun.com/ha-mc-server/seaweedfs:latest
          command: ["weed", "volume", "-mserver=seaweedfs-master:9333", "-dir=/data"]
          volumeMounts:
            - name: seaweedfs-volume-data
              mountPath: /data
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: seaweedfs-volume-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
