apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-volume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
        - name: seaweedfs-volume
          image: ccr.ccs.tencentyun.com/ha-mc-server/seaweedfs:latest
          command: ["weed", "volume", "-mserver=seaweedfs-master:9333", "-dir=/data"]
          volumeMounts:
            - name: seaweedfs-data
              mountPath: /data
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: seaweedfs-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
spec:
  selector:
    app: seaweedfs-volume
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
